name: Build and deploy workflow
on: [push]
jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t uliagareeva/homework_26:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_NAME }} --password-stdin
      - name: docker push
        run: docker push uliagareeva/homework_26:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: clone code
        uses: actions/checkout@v2

      - name: render configs
        run: |
          mkdir user
          cat docker-compose-ci.yaml | envsubst > user/docker-compose.yaml
          cat docker_config_ci.py | envsubst > user/docker_config.py

      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "user/docker-compose.yaml,user/docker_config.py"
          target: "hw26_ci"
          strip_components: 1

      - name: Deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd hw26_ci
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d
